export const FORMALITIES = [
  "",
  "Traspaso",
  "Matricula/Registro",
  "Translado Matricula / Registro",
  "Radicado Matricula / Registro",
  "Cambio de color",
  "Cambio de servicio",
  "Regrabar motor",
  "Regrabar chasis",
  "Transformación",
  "Duplicado licencia de transito",
  "Inscripción prenda",
  "Levantamiento de prenda",
  "Cancelación matricula / Registro",
  "Cambio de placas",
  "Duplicado de placas",
  "Rematricula",
  "Cambio de carroceria",
  "Otros",
];
